apiVersion: v2
appVersion: "1.0"
description: A Helm chart for opal-logging-service App
name: opal-logging-service
home: https://github.com/hmcts/opal-logging-service
version: 0.0.17
maintainers:
  - name: HMCTS opal team
dependencies:
  - name: java
    version: 5.3.0
    repository: 'oci://hmctspublic.azurecr.io/helm'
