openapi: 3.0.1
info:
  title: Opal Logging Service
  version: "1.0.0"
paths:
  /log/pdpo:
    post:
      summary: Record a personal data processing log entry
      operationId: recordPdpoLog
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PersonalDataProcessingLogDetails'
      responses:
        "201":
          description: Log created
components:
  schemas:
    PersonalDataProcessingLogDetails:
      type: object
      required:
        - created_by
        - business_identifier
        - created_at
        - ip_address
        - category
        - individuals
      properties:
        created_by:
          $ref: '#/components/schemas/ParticipantIdentifier'
        business_identifier:
          type: string
          maxLength: 250
        created_at:
          type: string
          format: date-time
        ip_address:
          type: string
        category:
          description: >
            Processing category. Values correspond to the TDIA list
            (Collection, Alteration, Consultation, Disclosure (including Transfers),
            Combination, Erasure) and are supplied in uppercase.
          $ref: '#/components/schemas/PersonalDataProcessingCategory'
        recipient:
          description: Must be supplied when `category` is DISCLOSURE; omit for all
            other categories.
          $ref: '#/components/schemas/ParticipantIdentifier'
        individuals:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/ParticipantIdentifier'
    ParticipantIdentifier:
      type: object
      required:
        - identifier
        - type
      properties:
        identifier:
          type: string
          maxLength: 50
        type:
          $ref: '#/components/schemas/IdentifierType'
    IdentifierType:
      type: object
      required:
        - type
      properties:
        type:
          type: string
          maxLength: 30
    PersonalDataProcessingCategory:
      type: string
      enum:
        - COLLECTION
        - ALTERATION
        - CONSULTATION
        - DISCLOSURE_TRANSFERS
        - COMBINATION
        - ERASURE
